apiVersion: apps/v1
kind: Deployment
metadata: 
    name: two-tier-app-deployment
    labels:
       app: two-tier-app
spec: 
  replicas: 4
  selectors:
      matchLables:
       app: two-tier-app

template:
  metadata:
     lables:
         app: two-tier-app

  specs:
   containers:
      -name: two-tier-app-ctr
       image: Akhileshsingh07/flasapp:latest
       env:
         -name: MY_HOST
         value: "mysql"
         -name: MYSQL_USER
         value: admin
         -name: MYSQL_PASSWORD
         value: admin 
         -name: MY_DB
         value: my_db

ports:
  -containerport: 5000
imagePullPolicy: Always
