apiVersion: v1
kind: service
metadata:
    name: two-tier-app-service

spec: 
    selector: 
       app: two-tier-app

    ports: 
      - protocols: TCP
        port : 80 # node port
        targetPort: 5000  #port of pod inside node
        nodePort: 30007 #any between 30k -32k -it is a port for outer traffic to access application.
    type: NodePort